# Generated by Django 5.1.7 on 2025-03-26 22:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discusion',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='discusion',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
