# Generated by Django 5.1.7 on 2025-03-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_topico_discusion_user_comentario_discusion_topico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
