# Generated by Django 5.1.7 on 2025-03-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_comentario_created_alter_comentario_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discusion',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='discusion',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
